[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = "8ftfAnTMo65PV8x4KcjPsGerL5yrmotcBiS6pEWAfJWJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matiseto/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
