[features]
seeds = false
skip-lint = false

[programs.devnet]
myepicproject = "9uJeg9wfWjti7chiHsJS7M289JsyxtjHCpAGFGf4amRt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/matiseto/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
